apiVersion: v1
kind: Secret
metadata:
  name: app-config
data:
  db.connection_timeout: NjBzCg==
  db.connection_method: aHR0cHMK
  db.port: MzU3OQo=
  db: ewogIGNvbm5lY3Rpb25fdGltZW91dDogIjYwcyIsCiAgY29ubmVjdGlvbl9tZXRob2Q6ICJodHRwcyIsCiAgcG9ydDogMzQ4MAp9Cg==

