apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-www
  labels:
    app: python-www
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-www
  template:
    metadata:
      labels:
        app: python-www
    spec:
      containers:
      - name: my-www
        image: hwchiu/netutils:python
        ports:
          - name: python-port
            containerPort: 8000
            protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: python-www
spec:
  type: ClusterIP
  selector:
    app: python-www
  ports:
  - name: www-port
    protocol: TCP
    port: 80
    targetPort: python-port

