apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: my-www
        image: ghost:4.41
        ports:
          - name: go-port
            containerPort: 2368
            protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
  - name: www-port
    protocol: TCP
    port: 80
    targetPort: go-port
