apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/local_data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-cluster-worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-pv
spec:
  replicas: 5
  selector:
    matchLabels:
      app: task-pv
  template:
    metadata:
      labels:
        app: task-pv
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: task-pv-container
          image: hwchiu/netutils:python
          ports:
            - containerPort: 8000
              name: "http-server"
          volumeMounts:
            - mountPath: "/config"
              name: task-pv-storage
