apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry-fail-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: private-registry-fail
  template:
    metadata:
      labels:
        app: private-registry-fail
    spec:
      containers:
      - name: my-www
        image: hwchiu/test:python
        ports:
          - containerPort: 8000
            protocol: "TCP"
        imagePullPolicy: Always
