apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: startup
  template:
    metadata:
      labels:
        app: startup
    spec:
      containers:
      - name: my-startup
        image: hwchiu/netutils:python
        ports:
        - name: python-port
          containerPort: 8972
          protocol: "TCP"
        startupProbe:
          httpGet:
            path: /haha
            port: python-port
          failureThreshold: 5
          periodSeconds: 5
 
