apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oom
  template:
    metadata:
      labels:
        app: oom
    spec:
      containers:
      - name: my-python
        image: hwchiu/netutils:python
        command: ["tail","/dev/zero"]
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
