apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-exampleip
  labels:
    app: rbac-exampleip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rbac-exampleip
  template:
    metadata:
      labels:
        app: rbac-exampleip
    spec:
      containers:
      - name: my-www
        image: hwchiu/kubectl-tools:1.20
      serviceAccountName: read-pod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-pod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: read-pod
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
